name: 每月抓取

on:
  workflow_dispatch:
  schedule:
  - cron: '11 5 26 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run startmonth.sh
        run: |
          bash ./startmonth.sh
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: $\{{secrets.GITHUB_TOKEN}}
          branch: main
